name: .NET

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish for win-x64
      run: dotnet publish -c ReleaseInvisible -r win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishReadyToRun=true
    - name: Publish for win-arm64
      run: dotnet publish -c ReleaseInvisible -r win-arm64 --self-contained true -p:PublishSingleFile=true -p:PublishReadyToRun=true
    - uses: actions/upload-artifact@v3
      with:
        name: release-win-x64
        path: |
          /home/runner/work/EnergyStar/EnergyStar/EnergyStar/bin/ReleaseInvisible/net6.0-windows/win-x64/publish/EnergyStar.exe
          /home/runner/work/EnergyStar/EnergyStar/EnergyStar/bin/ReleaseInvisible/net6.0-windows/win-x64/publish/icon.ico
    - uses: actions/upload-artifact@v3
      with:
        name: release-win-arm64
        path: |
          /home/runner/work/EnergyStar/EnergyStar/EnergyStar/bin/ReleaseInvisible/net6.0-windows/win-arm64/publish/EnergyStar.exe
          /home/runner/work/EnergyStar/EnergyStar/EnergyStar/bin/ReleaseInvisible/net6.0-windows/win-arm64/publish/icon.ico
